version: '3.9'

services:
  cassandra:
    image: cassandra:4.0
    ports:
      - 9042:9042
      - 7199:7199
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=local-perf-test
  alpine:
    image: alpine
    volumes:
      - cassandra-data:/var/lib/cassandra
volumes:
  cassandra-data:
